#!/bin/sh
# postinst script for rtlsdr-ogn

set -e


case "$1" in
    configure)
        if ! getent group ogn >/dev/null; then
            addgroup --quiet --system ogn
        fi
        if ! getent passwd ogn >/dev/null; then
            adduser --quiet --system --ingroup ogn --no-create-home ogn
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
